### ISSUE TITLE
Remove master branch

### ISSUE THREAD

**Issue by frantic** [mrkane27/sb#1]
Looks like you are using Github Pages to automatically publish `gh-pages` branch. Having `master` branch will only cause your troubles syncing your code.

Here's a trick you can do. In your repository [Settings/Branches](https://github.com/mrkane27/sb/settings/branches) select `gh-pages` as default branch

![image](https://cloud.githubusercontent.com/assets/192222/10567814/ccb832ce-75c2-11e5-9b12-80d594d8fa62.png)

and then remove `master` branch using `git push origin :master`

**Comment by mrkane27** [comment]
I was considering it actually, wasn't sure what to do: having a master branch would help with controlling when I "release", right? But you're right, possibly too much friction.

**Comment by mrkane27** [comment]
Done.
